development:
  adapter: sqlite3
  database: library_development
  pool: 5
  host: 5000

test:
  adapter: sqlite3
  database: library_development
  pool: 5
  host: 5000

production:
  adapter: sqlite3
  database: library_development
  pool: 5
  host: 5000
